Mar 08 Spell
marsfoundation/spark-spells pull request #35
Opened 2024-03-08 11:25 UTC by barrutko

2024-03-08 11:28 UTC, lucas-manuel requested changes

2024-03-08 11:28 UTC, lucas-manuel commented on src/proposals/20240308/SparkEthereum_20240308.t.sol
> +        ReserveConfig memory daiConfigBefore    = _findReserveConfigBySymbol(allConfigsBefore, 'DAI');
RM spaces

2024-03-08 11:30 UTC, barrutko commented on src/proposals/20240308/SparkEthereum_20240308.t.sol
> +        ReserveConfig memory daiConfigBefore    = _findReserveConfigBySymbol(allConfigsBefore, 'DAI');
done

2024-03-08 12:53 UTC, hexonaut approved these changes
Reviewed synchronously. Approving here for visibility.

2024-03-11 21:56 UTC, lucas-manuel approved these changes

2024-03-12 11:58 UTC, merged