[SC-340] Mar 20 Spell
marsfoundation/spark-spells pull request #37
Opened 2024-03-15 14:30 UTC by barrutko

**This spell (and tests) assumes that the previous spell will be executed first (06 Mar)**

2024-03-21 14:24 UTC, hexonaut requested changes

2024-03-21 14:24 UTC, hexonaut commented on src/interfaces/IOwnable.sol
> +}
For this one-off stuff we can just inline it.

2024-03-21 14:24 UTC, hexonaut commented on src/proposals/20240320/SparkEthereum_20240320.sol
> + * Votes:  TODO
Votes are up:

https://vote.makerdao.com/polling/QmVGDsvm
https://vote.makerdao.com/polling/QmYYoAMe

Forum post about the Morpho vault will be posted by BA soon. They can do changes without polling on this.

2024-03-21 23:20 UTC, hexonaut submitted a review, later dismissed
Good to deploy.

2024-03-22 17:09 UTC, hexonaut requested changes
Tested spell locally, and it's good. Sending off to govops team.

CI is failing though we need to remove the lib/ that was added.

2024-03-22 17:14 UTC, hexonaut approved these changes
Ok LGTM

2024-03-25 11:56 UTC, barrutko reviewed
Reviewed changes added on top of my commits. LGTM.

2024-03-25 12:37 UTC, hexonaut commented
Merging as we had to hand off the spell to @lucas-manuel part way.

2024-03-25 12:37 UTC, merged